// 宗門大殿：一次性匯入用的基礎資料（弟子花名冊 / 倉儲物資）
// 這份檔案只是「種子資料」：匯入後所有內容都以 Firebase 為準，
// 之後在網站上編輯不會回寫這裡。重複匯入時會自動略過同階級同名的弟子與同分類同名的物資。

export const ROSTER_SEED = [
  {"name":"諸葛雨荷","rank":"長老","title":"門主","root":"太陰","job":"武僧","path":"體修","realm":"金丹初期","master":""},
  {"name":"宙與","rank":"長老","title":"大長老傳功堂主","root":"木","job":"武僧","path":"體修","realm":"築基後期","master":""},
  {"name":"凌劍塵","rank":"長老","title":"二長老內務堂主","root":"金火","job":"道士","path":"劍修","realm":"金丹初期","master":""},
  {"name":"昌言","rank":"長老","title":"三長老外務堂主","root":"五行","job":"武僧","path":"佛修","realm":"築基圓滿","master":""},
  {"name":"凌劍曦","rank":"長老","title":"四長老執法堂主","root":"金","job":"醫師","path":"體修","realm":"金丹初期","master":""},
  {"name":"徐鯤","rank":"長老","title":"陣法堂主","root":"五行","job":"陣法師","path":"術修","realm":"築基後期","master":""},
  {"name":"鎏","rank":"長老","title":"煉丹堂主","root":"金木火","job":"煉丹師","path":"毒修","realm":"金丹初期","master":""},
  {"name":"深如鏡","rank":"長老","title":"煉器堂主","root":"金火","job":"鐵匠","path":"劍修","realm":"築基後期","master":""},
  {"name":"沈知非","rank":"長老","title":"制符堂主","root":"水","job":"制符師","path":"散修","realm":"築基中期","master":""},
  {"name":"方玄鞘","rank":"長老","title":"鬥戰堂主","root":"金土","job":"武僧","path":"體修","realm":"築基圓滿","master":""},
  {"name":"古岳方源","rank":"長老","title":"奇蟲堂主","root":"金木土","job":"蠱師","path":"邪修","realm":"金丹初期","master":""},
  {"name":"青娘","rank":"長老","title":"靈獸堂主","root":"木","job":"馴獸師","path":"毒修","realm":"築基中期","master":""},
  {"name":"陳微洛","rank":"長老","title":"情報堂主","root":"金火","job":"鐵匠","path":"劍修","realm":"築基圓滿","master":""},
  {"name":"林天衍","rank":"真傳","title":"內務堂","root":"天","job":"道士","path":"劍修","realm":"築基中期","master":"凌劍塵"},
  {"name":"田小穗","rank":"真傳","title":"內務堂","root":"木土","job":"醫師","path":"散修","realm":"煉氣六層","master":"凌劍塵"},
  {"name":"趙無塵","rank":"真傳","title":"內務堂","root":"火","job":"驅魔師","path":"劍修","realm":"煉氣圓滿","master":"凌劍塵"},
  {"name":"陸寒舟","rank":"真傳","title":"內務堂","root":"水土","job":"制符師","path":"劍修","realm":"煉氣八層","master":"凌劍塵"},
  {"name":"白若雪","rank":"真傳","title":"內務堂","root":"冰","job":"鑑定師","path":"劍修","realm":"煉氣圓滿","master":"凌劍塵"},
  {"name":"寧照塵","rank":"真傳","title":"鬥戰堂","root":"雷","job":"驅魔師","path":"術修","realm":"煉氣七層","master":"凌劍塵"},
  {"name":"沈孤鶴","rank":"真傳","title":"鬥戰堂","root":"金","job":"道士","path":"劍修","realm":"煉氣七層","master":"凌劍塵"},
  {"name":"唐不平","rank":"真傳","title":"煉器堂","root":"雷","job":"鐵匠","path":"劍修","realm":"煉氣圓滿","master":"凌劍塵"},
  {"name":"展日召","rank":"真傳","title":"外務堂","root":"金木水火","job":"驅魔師","path":"散修","realm":"築基初期","master":"昌言"},
  {"name":"楚無懼","rank":"真傳","title":"外務堂","root":"土","job":"偽裝師","path":"散修","realm":"築基初期","master":"昌言"},
  {"name":"許無歸","rank":"真傳","title":"傳功堂","root":"空","job":"道士","path":"散修","realm":"築基初期","master":"宙與"},
  {"name":"高如玄","rank":"真傳","title":"傳功堂","root":"雷","job":"道士","path":"術修","realm":"築基後期","master":"宙與"},
  {"name":"鐵頭","rank":"真傳","title":"傳功堂","root":"土","job":"鐵匠","path":"體修","realm":"築基中期","master":"宙與"},
  {"name":"言青","rank":"真傳","title":"陣法堂","root":"火","job":"陣法師","path":"術修","realm":"煉氣圓滿","master":"鎏"},
  {"name":"沈墨","rank":"真傳","title":"煉丹堂","root":"木","job":"煉丹師","path":"術修","realm":"築基圓滿","master":"鎏"},
  {"name":"朱小稻","rank":"真傳","title":"煉丹堂","root":"毒","job":"煉丹師","path":"毒修","realm":"煉氣六層","master":"鎏"},
  {"name":"石娃","rank":"真傳","title":"煉丹堂","root":"金","job":"煉丹師","path":"散修","realm":"煉氣八層","master":"鎏"},
  {"name":"陳小桃","rank":"真傳","title":"煉丹堂","root":"火","job":"煉丹師","path":"散修","realm":"煉氣五層","master":"鎏"},
  {"name":"黑石","rank":"真傳","title":"鬥戰堂","root":"木土","job":"農夫","path":"散修","realm":"煉氣圓滿","master":"方玄鞘"},
  {"name":"阿烈","rank":"真傳","title":"鬥戰堂","root":"金","job":"武僧","path":"體修","realm":"煉氣圓滿","master":"方玄鞘"},
  {"name":"圖罕","rank":"真傳","title":"鬥戰堂","root":"風","job":"武僧","path":"體修","realm":"煉氣圓滿","master":"方玄鞘"},
  {"name":"達穆","rank":"真傳","title":"鬥戰堂","root":"土","job":"武僧","path":"體修","realm":"煉氣圓滿","master":"方玄鞘"},
  {"name":"沈明鏡","rank":"真傳","title":"鬥戰堂","root":"鬥","job":"武僧","path":"佛修","realm":"煉氣圓滿","master":"方玄鞘"},
  {"name":"柳眠煙","rank":"真傳","title":"醫療堂","root":"木","job":"醫師","path":"毒修","realm":"築基中期","master":"恢安命"},
  {"name":"敖善命","rank":"真傳","title":"醫療堂","root":"火木土","job":"醫師","path":"體修","realm":"煉氣八層","master":"恢安命"},
  {"name":"蘇清荷","rank":"真傳","title":"醫療堂","root":"木水","job":"醫師","path":"散修","realm":"煉氣七層","master":"恢安命"},
  {"name":"柳映月","rank":"真傳","title":"醫療堂","root":"陰","job":"醫師","path":"散修","realm":"煉氣九層","master":"恢安命"},
  {"name":"柴德","rank":"真傳","title":"情報堂","root":"木火","job":"會計師","path":"散修","realm":"築基後期","master":"陳微洛"},
  {"name":"賏","rank":"真傳","title":"情報堂","root":"","job":"書法師","path":"術修","realm":"","master":"陳微洛"},
  {"name":"武","rank":"真傳","title":"情報堂","root":"鬥","job":"偽裝師","path":"體修","realm":"煉氣圓滿","master":"陳微洛"},
  {"name":"柏舟","rank":"真傳","title":"情報堂","root":"木","job":"占卜師","path":"散修","realm":"煉氣三層","master":"陳微洛"},
  {"name":"唐墨川","rank":"內門","title":"","root":"毒","job":"醫師","path":"毒修","realm":"煉氣六層","master":""},
  {"name":"柳映心","rank":"內門","title":"","root":"木","job":"驅魔師","path":"劍修","realm":"煉氣三層","master":""},
  {"name":"林照野","rank":"內門","title":"","root":"火","job":"道士","path":"術修","realm":"煉氣五層","master":""},
  {"name":"巫月","rank":"內門","title":"","root":"風","job":"蠱師","path":"巫修","realm":"煉氣圓滿","master":""},
  {"name":"蘇婉","rank":"內門","title":"","root":"水","job":"醫師","path":"術修","realm":"煉氣圓滿","master":""},
  {"name":"子瑜","rank":"內門","title":"","root":"雷","job":"道士","path":"劍修","realm":"煉氣圓滿","master":""},
  {"name":"仇遠","rank":"內門","title":"","root":"火","job":"武僧","path":"體修","realm":"煉氣圓滿","master":""},
  {"name":"顧長青","rank":"內門","title":"","root":"火","job":"煉丹師","path":"術修","realm":"煉氣圓滿","master":""},
  {"name":"白映雪","rank":"內門","title":"","root":"光","job":"符咒師","path":"術修","realm":"煉氣圓滿","master":""},
  {"name":"沈青川","rank":"內門","title":"","root":"雷","job":"道士","path":"術修","realm":"煉氣圓滿","master":""},
  {"name":"高鐵牛","rank":"內門","title":"","root":"金土","job":"鐵匠","path":"體修","realm":"煉氣九層","master":""},
  {"name":"方知遠","rank":"內門","title":"","root":"木","job":"陣法師","path":"術修","realm":"煉氣圓滿","master":""},
  {"name":"柳清漪","rank":"外門","title":"","root":"水","job":"書法師","path":"術修","realm":"煉氣八層","master":""},
  {"name":"韓烈山","rank":"外門","title":"","root":"火","job":"鐵匠","path":"術修","realm":"煉氣圓滿","master":""},
  {"name":"石鐵衣","rank":"外門","title":"","root":"土","job":"鐵匠","path":"體修","realm":"煉氣圓滿","master":""},
  {"name":"蘇夜白","rank":"外門","title":"","root":"冰","job":"驅魔師","path":"術修","realm":"煉氣七層","master":""},
  {"name":"葉秋辭","rank":"外門","title":"","root":"風","job":"書法師","path":"音修","realm":"煉氣九層","master":""},
  {"name":"李玄松","rank":"外門","title":"","root":"金土","job":"陣法師","path":"術修","realm":"煉氣七層","master":""},
  {"name":"陳大山","rank":"外門","title":"","root":"土","job":"武僧","path":"體修","realm":"煉氣八層","master":""},
  {"name":"何小雨","rank":"外門","title":"","root":"金水","job":"醫師","path":"術修","realm":"煉氣八層","master":""},
  {"name":"周阿福","rank":"外門","title":"","root":"金火","job":"煉丹師","path":"術修","realm":"煉氣七層","master":""},
  {"name":"朱阿禾","rank":"外門","title":"","root":"天","job":"馴獸師","path":"散修","realm":"煉氣七層","master":""},
  {"name":"柳阿盼","rank":"外門","title":"","root":"風","job":"占卜師","path":"術修","realm":"煉氣八層","master":""},
  {"name":"蘭陵","rank":"外門","title":"","root":"音","job":"書法師","path":"音修","realm":"煉氣九層","master":""},
  {"name":"仇景","rank":"外門","title":"","root":"金","job":"書法師","path":"散修","realm":"煉氣八層","master":""},
  {"name":"仇衡","rank":"外門","title":"","root":"木","job":"偽裝師","path":"散修","realm":"煉氣九層","master":""},
  {"name":"仇逸","rank":"外門","title":"","root":"水","job":"驅魔師","path":"散修","realm":"煉氣九層","master":""},
  {"name":"仇川","rank":"外門","title":"","root":"土","job":"道士","path":"術修","realm":"煉氣七層","master":""},
  {"name":"唐笑生","rank":"外門","title":"","root":"火","job":"馴獸師","path":"散修","realm":"煉氣七層","master":""},
  {"name":"阿蕖","rank":"外門","title":"","root":"水","job":"醫師","path":"術修","realm":"煉氣七層","master":""},
  {"name":"屈墨","rank":"外門","title":"","root":"風","job":"鑑定師","path":"術修","realm":"煉氣九層","master":""},
  {"name":"樂夷","rank":"外門","title":"","root":"火","job":"書法師","path":"音修","realm":"煉氣八層","master":""},
  {"name":"阿林嫂","rank":"外門","title":"","root":"木水","job":"煉丹師","path":"散修","realm":"煉氣七層","master":""},
  {"name":"易牙","rank":"外門","title":"","root":"灶","job":"廚師","path":"術修","realm":"煉氣圓滿","master":""},
  {"name":"柯冬凱","rank":"記名","title":"","root":"金水","job":"鑑定師","path":"術修","realm":"煉氣四層","master":""},
  {"name":"連梓揚","rank":"記名","title":"","root":"木火","job":"煉丹師","path":"術修","realm":"煉氣五層","master":""},
  {"name":"朱詩思","rank":"記名","title":"","root":"木水土","job":"醫師","path":"術修","realm":"煉氣三層","master":""},
  {"name":"林裕陽","rank":"記名","title":"","root":"火土","job":"鐵匠","path":"體修","realm":"煉氣五層","master":""},
  {"name":"嚴智熙","rank":"記名","title":"","root":"雷","job":"劍修","path":"劍修","realm":"煉氣六層","master":""},
  {"name":"李世慧","rank":"記名","title":"","root":"水木","job":"占卜師","path":"術修","realm":"煉氣四層","master":""},
  {"name":"鄭成詠","rank":"記名","title":"","root":"土木","job":"陣法師","path":"術修","realm":"煉氣五層","master":""},
  {"name":"武宙瑜","rank":"記名","title":"","root":"金火","job":"武僧","path":"體修","realm":"煉氣六層","master":""},
  {"name":"廖樂全","rank":"記名","title":"","root":"木","job":"馴獸師","path":"散修","realm":"煉氣三層","master":""},
  {"name":"顏雨青","rank":"記名","title":"","root":"水","job":"符咒師","path":"術修","realm":"煉氣四層","master":""},
  {"name":"文美祺","rank":"記名","title":"","root":"木水火","job":"書法師","path":"術修","realm":"煉氣三層","master":""},
  {"name":"曾佑麟","rank":"記名","title":"","root":"金土","job":"鐵匠","path":"體修","realm":"煉氣五層","master":""},
  {"name":"賈楊軍","rank":"記名","title":"","root":"火","job":"蠱師","path":"毒修","realm":"煉氣六層","master":""},
  {"name":"高梓龍","rank":"記名","title":"","root":"金","job":"道士","path":"劍修","realm":"煉氣七層","master":""},
  {"name":"賀靜穎","rank":"記名","title":"","root":"水木","job":"醫師","path":"術修","realm":"煉氣一層","master":""},
  {"name":"林胤楷","rank":"記名","title":"","root":"土","job":"驅魔師","path":"散修","realm":"煉氣三層","master":""},
  {"name":"麥俊懿","rank":"記名","title":"","root":"金火","job":"鐵匠","path":"體修","realm":"煉氣二層","master":""},
  {"name":"孫一韻","rank":"記名","title":"","root":"音","job":"書法師","path":"音修","realm":"煉氣二層","master":""},
  {"name":"游思銘","rank":"記名","title":"","root":"木土","job":"陣法師","path":"術修","realm":"煉氣五層","master":""},
  {"name":"鍾唐芝","rank":"記名","title":"","root":"木火","job":"符咒師","path":"散修","realm":"煉氣六層","master":""},
  {"name":"芳祺","rank":"記名","title":"","root":"木水","job":"馴獸師","path":"散修","realm":"煉氣七層","master":""},
  {"name":"洪耿楨","rank":"記名","title":"","root":"金火","job":"武僧","path":"體修","realm":"煉氣四層","master":""},
  {"name":"向禹秋","rank":"記名","title":"","root":"水","job":"占卜師","path":"術修","realm":"煉氣五層","master":""},
  {"name":"湯俊暉","rank":"記名","title":"","root":"火土","job":"煉丹師","path":"散修","realm":"煉氣五層","master":""},
  {"name":"韋玟萱","rank":"記名","title":"","root":"木","job":"醫師","path":"散修","realm":"煉氣五層","master":""},
  {"name":"陶採瀅","rank":"記名","title":"","root":"木水","job":"樂師","path":"音修","realm":"煉氣四層","master":""},
  {"name":"阮心龍","rank":"記名","title":"","root":"金","job":"驅魔師","path":"佛修","realm":"煉氣六層","master":""},
  {"name":"洪贊琛","rank":"記名","title":"","root":"火土","job":"鐵匠","path":"體修","realm":"煉氣三層","master":""},
  {"name":"田作奇","rank":"記名","title":"","root":"金水","job":"偽裝師","path":"散修","realm":"煉氣七層","master":""},
  {"name":"胡沈根","rank":"記名","title":"","root":"木","job":"蠱師","path":"散修","realm":"煉氣三層","master":""},
  {"name":"范毓芸","rank":"記名","title":"","root":"木水","job":"書法師","path":"散修","realm":"煉氣五層","master":""},
  {"name":"黃永華","rank":"記名","title":"","root":"金土","job":"武僧","path":"佛修","realm":"煉氣四層","master":""},
  {"name":"歐輔峯","rank":"記名","title":"","root":"金","job":"道士","path":"劍修","realm":"煉氣五層","master":""},
  {"name":"姚嘉瀧","rank":"記名","title":"","root":"水火","job":"道士","path":"散修","realm":"煉氣六層","master":""},
  {"name":"顏炫嶽","rank":"記名","title":"","root":"火","job":"陣法師","path":"巫修","realm":"煉氣四層","master":""},
  {"name":"傅忠志","rank":"記名","title":"","root":"水土","job":"陣法師","path":"散修","realm":"煉氣五層","master":""},
  {"name":"方筱潞","rank":"記名","title":"","root":"木水","job":"符咒師","path":"體修","realm":"煉氣五層","master":""},
  {"name":"錢朝慶","rank":"記名","title":"","root":"金火","job":"煉丹師","path":"劍修","realm":"煉氣六層","master":""},
  {"name":"黃銘怡","rank":"記名","title":"","root":"木","job":"醫師","path":"散修","realm":"煉氣三層","master":""},
  {"name":"翁阿強","rank":"記名","title":"","root":"金土","job":"偽裝師","path":"巫修","realm":"煉氣四層","master":""},
  {"name":"莫君紅","rank":"記名","title":"","root":"火","job":"蠱師","path":"散修","realm":"煉氣三層","master":""},
  {"name":"彭亦鳴","rank":"記名","title":"","root":"水","job":"符咒師","path":"巫修","realm":"煉氣五層","master":""},
  {"name":"段景程","rank":"記名","title":"","root":"金木","job":"馴獸師","path":"散修","realm":"煉氣五層","master":""},
  {"name":"廖有緣","rank":"記名","title":"","root":"木土","job":"馴獸師","path":"術修","realm":"煉氣二層","master":""},
  {"name":"羅紓雨","rank":"記名","title":"","root":"水","job":"符咒師","path":"散修","realm":"煉氣一層","master":""},
  {"name":"董學國","rank":"記名","title":"","root":"火土","job":"書法師","path":"散修","realm":"煉氣七層","master":""},
  {"name":"黃昭福","rank":"記名","title":"","root":"金土","job":"偽裝師","path":"散修","realm":"煉氣六層","master":""},
  {"name":"薛才望","rank":"記名","title":"","root":"金","job":"鑑定師","path":"劍修","realm":"煉氣一層","master":""},
  {"name":"柯宗尚","rank":"記名","title":"","root":"火","job":"鐵匠","path":"體修","realm":"煉氣一層","master":""},
  {"name":"黎和友","rank":"記名","title":"","root":"木水","job":"符咒師","path":"散修","realm":"煉氣二層","master":""},
  {"name":"郭贛毅","rank":"記名","title":"","root":"土","job":"偽裝師","path":"散修","realm":"煉氣三層","master":""},
  {"name":"江芳銘","rank":"記名","title":"","root":"木火","job":"醫師","path":"毒修","realm":"煉氣六層","master":""},
  {"name":"吳崴涵","rank":"記名","title":"","root":"水","job":"符咒師","path":"散修","realm":"煉氣五層","master":""},
  {"name":"陳鳴巍","rank":"記名","title":"","root":"金","job":"驅魔師","path":"散修","realm":"煉氣三層","master":""},
  {"name":"賴鄭怡","rank":"記名","title":"","root":"木水","job":"陣法師","path":"散修","realm":"煉氣五層","master":""},
  {"name":"傅鳴軒","rank":"記名","title":"","root":"火土","job":"驅魔師","path":"體修","realm":"煉氣六層","master":""},
  {"name":"李曉藍","rank":"記名","title":"","root":"水","job":"書法師","path":"散修","realm":"煉氣五層","master":""},
  {"name":"辜典康","rank":"記名","title":"","root":"金木","job":"符咒師","path":"音修","realm":"煉氣三層","master":""},
  {"name":"巫學矩","rank":"記名","title":"","root":"木","job":"醫師","path":"散修","realm":"煉氣四層","master":""},
  {"name":"張於清","rank":"記名","title":"","root":"木水","job":"書法師","path":"散修","realm":"煉氣二層","master":""},
  {"name":"田秀洋","rank":"記名","title":"","root":"金土","job":"陣法師","path":"散修","realm":"煉氣四層","master":""},
  {"name":"紀紅男","rank":"記名","title":"","root":"火","job":"驅魔師","path":"音修","realm":"煉氣六層","master":""},
  {"name":"伍敦麗","rank":"記名","title":"","root":"木水火","job":"煉丹師","path":"佛修","realm":"煉氣五層","master":""},
  {"name":"孔姝恆","rank":"記名","title":"","root":"水木","job":"書法師","path":"佛修","realm":"煉氣七層","master":""},
  {"name":"全樑歡","rank":"記名","title":"","root":"土","job":"偽裝師","path":"毒修","realm":"煉氣三層","master":""},
  {"name":"鄭柔樂","rank":"記名","title":"","root":"木","job":"蠱師","path":"散修","realm":"煉氣三層","master":""},
  {"name":"范弘瑞","rank":"記名","title":"","root":"金火","job":"鑑定師","path":"散修","realm":"煉氣五層","master":""},
  {"name":"夏泓迪","rank":"記名","title":"","root":"水","job":"武僧","path":"佛修","realm":"煉氣三層","master":""},
  {"name":"康志鋮","rank":"記名","title":"","root":"火土","job":"蠱師","path":"巫修","realm":"煉氣六層","master":""},
  {"name":"朱誠越","rank":"記名","title":"","root":"金木","job":"馴獸師","path":"散修","realm":"煉氣七層","master":""},
  {"name":"魏姿汝","rank":"記名","title":"","root":"木水","job":"蠱師","path":"毒修","realm":"煉氣四層","master":""},
  {"name":"陸胤涵","rank":"記名","title":"","root":"雷","job":"驅魔師","path":"術修","realm":"煉氣二層","master":""},
  {"name":"雷柏春","rank":"記名","title":"","root":"金","job":"鐵匠","path":"劍修","realm":"煉氣五層","master":""},
  {"name":"韋書陽","rank":"記名","title":"","root":"木土","job":"偽裝師","path":"散修","realm":"煉氣四層","master":""},
  {"name":"盧以丹","rank":"記名","title":"","root":"木火","job":"蠱師","path":"散修","realm":"煉氣四層","master":""},
  {"name":"姜詩綺","rank":"記名","title":"","root":"水","job":"符咒師","path":"散修","realm":"煉氣六層","master":""},
  {"name":"洪子建","rank":"記名","title":"","root":"金土","job":"占卜師","path":"散修","realm":"煉氣三層","master":""},
  {"name":"涂子荻","rank":"記名","title":"","root":"木","job":"醫師","path":"散修","realm":"煉氣一層","master":""},
  {"name":"史祥榮","rank":"記名","title":"","root":"金火","job":"鐵匠","path":"體修","realm":"煉氣六層","master":""},
  {"name":"顏競搏","rank":"記名","title":"","root":"金","job":"道士","path":"劍修","realm":"煉氣六層","master":""},
];

export const WAREHOUSE_SEED = [
  {"category":"丹藥","name":"築基丹","qty":1,"effect":""},
  {"category":"丹藥","name":"一品洗髓丹","qty":31,"effect":""},
  {"category":"丹藥","name":"一品易筋丹","qty":259,"effect":""},
  {"category":"丹藥","name":"一品解毒丹","qty":30,"effect":""},
  {"category":"丹藥","name":"二品大力丸","qty":50,"effect":"服用後十分鐘內根骨+1（單次最多服用一顆）"},
  {"category":"丹藥","name":"二品聚氣丹","qty":700,"effect":""},
  {"category":"丹藥","name":"二品回春丹","qty":580,"effect":""},
  {"category":"丹藥","name":"三品回靈丹","qty":50,"effect":"快速回復100靈力"},
  {"category":"丹藥","name":"四品玄澤培元丸","qty":7,"effect":"解毒丹，對瘴氣尤為有效"},
  {"category":"丹藥","name":"二品固本丹","qty":360,"effect":""},
  {"category":"法器","name":"馭獸令牌","qty":10,"effect":""},
  {"category":"法器","name":"迷霧鏡","qty":1,"effect":"每天一次，持有者可以用附贈動作照向某個生物，進行魅力對抗（DC12），成功使目標暫時「看不見」持有者三分鐘，但持有者移動時目標能聽見聲音。鏡子背面刻著「太上製」三個小字。"},
  {"category":"法器","name":"三品黑煞劍","qty":1,"effect":"法劍，劍身環繞陰寒之氣，品質不錯"},
  {"category":"法器","name":"三品開山雙錘","qty":1,"effect":"重達三百斤，攻擊力驚人"},
  {"category":"法器","name":"三品厚土盾","qty":1,"effect":"防禦法器，能展開土黃色護罩"},
  {"category":"材料","name":"龍血","qty":3,"effect":""},
  {"category":"材料","name":"龍膽","qty":1,"effect":""},
  {"category":"材料","name":"漿果酒","qty":1,"effect":""},
  {"category":"符咒","name":"⭐黃巾力士符","qty":3,"effect":""},
  {"category":"符咒","name":"二品護身符","qty":5,"effect":""},
  {"category":"符咒","name":"三品岩甲符","qty":3,"effect":"能在身體表面形成岩石鎧甲"},
];

// ===== 宗門基本資料 =====
// 門派層級的資訊：等級、聲望、護山大陣、敵對勢力。匯入後同樣以 Firebase 為準。
export const SECT_SEED = {
  name: "無相門",
  level: "三級",
  reputation: 10500,
  formation: "五行幻獸大陣",
  enemies: ["六道聯盟", "血手堂", "虎嘯門", "反虎嘯門大聯盟", "羅睺教"]
};

// ===== 宗門設施 =====
// upkeepKind：month＝每月固定開銷、once＝用一次扣一次、none＝不需靈石
// upkeepGrade 對應靈石國庫的四個等級鍵（low／mid／high／extreme）
// capMax 有填的才會畫容量條（目前只有靈獸園與修練道場有明確上限）
export const FACILITY_SEED = [
  {
    name: "山門", level: "三級", spec: "護山大陣：五行幻獸大陣",
    fn: "幻化出四階靈獸，主動困住並攻擊陣中生靈，對築基大圓滿以下修為有效。",
    upkeepKind: "month", upkeepGrade: "mid", upkeepQty: 500,
    tokens: [], limit: "", capNow: null, capMax: null, capUnit: ""
  },
  {
    name: "靈獸園", level: "三級", spec: "靈獸數量 6/20",
    fn: "馴化四階以下靈獸，並提高其進階速度二倍。",
    upkeepKind: "month", upkeepGrade: "low", upkeepQty: 5000,
    tokens: ["馭獸令牌"],
    limit: "每塊馭獸令牌需綁定一隻靈獸，且僅有持有馭獸令牌者方能使喚靈獸。",
    capNow: 6, capMax: 20, capUnit: "隻"
  },
  {
    name: "養蟲房", level: "三級", spec: "1 棟房子",
    fn: "馴服四階級四階以下奇蟲，並提高進階速度二倍。",
    upkeepKind: "month", upkeepGrade: "low", upkeepQty: 8000,
    tokens: ["掌門腰牌", "養蟲房令牌"], limit: "", capNow: null, capMax: null, capUnit: ""
  },
  {
    name: "修練道場", level: "三級", spec: "容納 50 人",
    fn: "提高築基中期以下修士修練速度三成、築基中期以上無作用。",
    upkeepKind: "month", upkeepGrade: "mid", upkeepQty: 40,
    tokens: [], limit: "", capNow: null, capMax: 50, capUnit: "人"
  },
  {
    name: "練功房", level: "三級", spec: "1 間",
    fn: "可提升掌門修練速度五成。",
    upkeepKind: "month", upkeepGrade: "low", upkeepQty: 8000,
    tokens: ["掌門鐵板指"], limit: "", capNow: null, capMax: null, capUnit: ""
  },
  {
    name: "參悟室", level: "三級", spec: "1 間房間",
    fn: "提升築基成功機率 3 成。",
    upkeepKind: "once", upkeepGrade: "mid", upkeepQty: 5000,
    tokens: ["掌門腰牌", "參悟室令牌"], limit: "", capNow: null, capMax: null, capUnit: ""
  },
  {
    name: "藏經閣", level: "三級", spec: "4 間房間",
    fn: "每月生成高階功法秘笈一本、可修復神通法術功法秘笈一本；每月生成三階丹方、器方、符方各一份，可修復四階丹方、器方、符方，可修復晉國範圍內藏寶圖。",
    upkeepKind: "month", upkeepGrade: "mid", upkeepQty: 400,
    tokens: ["掌門板指", "藏經閣令牌"], limit: "", capNow: null, capMax: null, capUnit: ""
  },
  {
    name: "靈田", level: "三級", spec: "30 畝",
    fn: "提高農作物生長週期四倍，每個月收穫二次，每次產量九千斤。",
    upkeepKind: "month", upkeepGrade: "mid", upkeepQty: 10,
    tokens: [], limit: "", capNow: null, capMax: null, capUnit: ""
  },
  {
    name: "靈藥圃", level: "三級", spec: "四畝",
    fn: "加速四階以下靈藥生長速度六倍。加速四階靈藥生長速度三倍。四階以上無效果。",
    upkeepKind: "month", upkeepGrade: "mid", upkeepQty: 50,
    tokens: ["掌門腰牌", "靈藥圃令牌"], limit: "", capNow: null, capMax: null, capUnit: ""
  },
  {
    name: "煉丹房", level: "三級", spec: "1 棟房子",
    fn: "四階以下靈丹成丹率百分之百。四階靈丹成丹率提升百分之三十。五階靈丹成丹率提升百分之十。五階以上無效果。",
    upkeepKind: "month", upkeepGrade: "low", upkeepQty: 8000,
    tokens: ["掌門腰牌", "煉丹房令牌"], limit: "", capNow: null, capMax: null, capUnit: ""
  },
  {
    name: "制符室", level: "三級", spec: "1 棟房子",
    fn: "四階符咒成功率提升三成，五階符咒成功率提升一成，五階以上無效果。",
    upkeepKind: "month", upkeepGrade: "low", upkeepQty: 8000,
    tokens: ["掌門腰牌", "制符室令牌"], limit: "", capNow: null, capMax: null, capUnit: ""
  }
];
